repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: detect-private-key

-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.8
    hooks:
    -   id: pymarkdown
        args:
          - scan

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
    -    id: golangci-lint
         name: golangci-lint
         description: Fast linters runner for Go.
         entry: golangci-lint run
         types: [go]
         language: golang
         pass_filenames: false
